# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#versioning-strategy

version: 2
updates:
  # Keep the Java dependencies up to date
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "master"
    labels:
      - "java dependencies"
    groups:
      java:
        applies-to: version-updates
        patterns:
          - "*"       # A wildcard that matches all dependencies in the package
  
  # Keep the Java dependencies up to date
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/zero-bounce-sdk/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "master"
    labels:
      - "java dependencies"
    groups:
      java:
        applies-to: version-updates
        patterns:
          - "*"       # A wildcard that matches all dependencies in the package

  # Keep the Github Actions dependencies up to date
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "master"
    labels:
      - "github dependencies"
    groups:
      github:
        applies-to: version-updates
        patterns:
          - "*"       # A wildcard that matches all dependencies in the package
