name: Auto Assign

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  add-reviewers:
    name: Auto assign reviewers
    runs-on: ubuntu-latest
    steps:
      # Set the author as the assignee of the PR.
      - uses: kentaro-m/auto-assign-action@v2.0.0
